### ISSUE TITLE
Document how to configure environment variables

### ISSUE THREAD

**Issue by bkeepers** [tcbyrd/probot-lambda#1]
README should include docs on setting `APP_ID` and `WEBHOOK_SECRET`

**Comment by bkeepers** [comment]
I ended up configuring it by setting the environment variables in the AWS console:

![lambda_management_console](https://user-images.githubusercontent.com/173/28475886-ac2ea196-6e13-11e7-841c-9ebe8f7b1e25.png)


It'd be cool if there was a programatic way to do it, either through the `aws` or `sls` CLIs (e.g. like `heroku config;set`)

**Comment by tcbyrd** [comment]
Updated the [README](https://github.com/tcbyrd/probot-lambda/blob/master/README.md#demo-setup) to reflect two different options:

 - In the `serverless.yml` file nested under `functions: probot: environment:` (I moved the example into the right spot. When you removed the comments from the previous example, it didn't nest it under the function properly).
 - Using the AWS CLI in the [`update-function-cofiguration`](http://docs.aws.amazon.com/cli/latest/reference/lambda/update-function-configuration.html) method:
    ```shell
    # Example
    aws lambda update-function-configuration --function-name lambda-probot-dev-probot --environment "Variables={APP_ID=0000,WEBHOOK_SECRET=development}"
    ```
